---
title: "Publications"
output: html_document
---


Kang, et al., “Electrophoretic cytopathology resolves ERB2 forms with single-cell”, NPJ Precision Oncology, 2018.

Perttula, et al., “Lipidomic features associated with colorectal cancer in a prospective cohort”, BMC Cancer, 2018.

Petrick, et al., “An untargeted metabolomics method for archived newborn dried blood spots in epidemiological studies”, Metabolomics, 2017.

Petrick, et al., “Metabolomics of Neonatal Blood Spots Reveals Lipid Associations with Pediatric Acute Lymphoblastic Leukemia,” IJE, 2018. Submitted for review.

Schiffman et al., “SIDEseq: a cell similarity measure defined by shared identified differentially expressed genes for single-cell RNA-sequencing data”, Statistics in Biosciences, 2017.

Schiffman et al., “Identification of gene expression predictors of occupational benzene exposure,” PLOS ONE, 2018.

Schiffman et al., “Data-adaptive pipeline for filtering and normalizing metabolomics data.,” bioRxiv, 2018, doi: https://doi.org/10.1101/387365.

Yano, et al., “Untargeted Adductomics of Cys34 Modification to Human Serum Albumin in Newborn Dried Blood Spots,” ABC, 2018. Submitted for review.

